// src/App.tsx
import './App.scss';
import Contact from './components/Contact';
import Experiences from './components/Experiences';
import Landing from "./components/Landing";
import NavigationBar from './components/Nav';
import Projects from './components/Projects';

function App() {
  return (
    <>
      <NavigationBar />
      <Landing />
      <Projects />
      <Experiences />
      <Contact />
    </>
  );
}

export default App;

// src/App.vue
<script setup lang="ts">
import Contact from './components/Contact.vue';
import Experience from './components/Experiences.vue';
import Landing from './components/Landing.vue';
import NavigationBar from './components/NavigationBar.vue';
import Projects from './components/Projects.vue';
</script>

<template>
    <NavigationBar />
    <Landing />
    <Projects />
    <Experience />
    <Contact />
</template>

<style>
a {
    text-decoration: none;
    color: var(--font-color);
}

a:hover {
    color: var(--link-hover-color);
}
</style>
